transform:
  target: dev
  outputs:
    dev:
      account: "YX69744"
      database: AIRBYTE_DATABASE
      password: "Arthur#123"
      role: AIRBYTE_ROLE
      schema: PUBLIC
      threads: 12
      type: snowflake
      user: Arthur
      warehouse: AIRBYTE_WAREHOUSE
